version: 2

models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        description: "The unique identifier for each listing."
        tests:
          - not_null
          - unique