version: 2

models:
  - name: dim_listings_cleansed
    columns:

      - name: listing_id
        description: "The unique identifier for each listing."
        tests:
          - not_null
          - unique

      - name: host_id
        description: "The unique identifier for each host. This is a foreign key to the dim_hosts_cleansed table."
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      
      - name: room_type
        tests:
          - accepted_values:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
              severity: warn
